# yaml-language-server: $schema=https://tangled.org/strings/@zerolimits.dev/3lyzzt7nqdm22/raw
when:
  - event: [push, pull_request]
    branch: [main]

engine: nixery

dependencies:
  nixpkgs:
    - bun
    - nodejs

steps:
  - name: Build the site
    command: bun run build
  - name: Deploy the site
    command: bunx wrangler deploy
